#!/usr/bin/env ansible-playbook
---
- name: Install Java and Coursier to install scala
  hosts: sandboxes
  become: True
  tasks:
    - name: Download Coursier
      ansible.builtin.get_url:
        url: https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz
        dest: /opt/cs.gz
    - name: "Check if cs exists"
      stat:
        path: "/opt/cs"
      register: result
    - name: Decompress Coursier
      ansible.builtin.shell: "[ -f /opt/cs ] || gzip -d /opt/cs.gz"
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)
      args:
        chdir: /opt
    - name: Create symlink to make Coursier available
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)
      ansible.builtin.file:
        src: /opt/cs
        dest: /usr/local/bin/cs
        state: link
    - name: Changing perm, adding "+x"
      ansible.builtin.file: 
        dest: /opt/cs 
        mode: a+x
- name: Install Scala and Java with Coursier
  hosts: sandboxes
  become: False
  tasks:
    - name: "Check if scala exists"
      stat:
        path: "{{ ansible_env.HOME }}/.local/share/coursier/bin/scala"
      register: result
    - name: Install scala with Coursier if is not installed
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)
      ansible.builtin.shell: cs setup --yes --jvm adopt:11
- name: Download resources
  hosts: sandboxes
  become: False
  tasks:
    - name: Install ruby to install Jekyll
      become: True
      ansible.builtin.package:
        name:
          - ruby-full
          - zlib1g-dev
          - make
        update_cache: True
    - name: Install latest available version of jekyll
      community.general.gem:
        name: jekyll
        state: latest         
        norc: True
...

